baseURL = "https://myc3.life/"
languageCode = "en-gb"
title = "My C3"

theme = "hugo-creative-portfolio-theme"

[params]
    style = "default"
    copyright = "&copy;2017 The C3"
    sidebarAbout = [
        "The home for C3 members"
    ]
    
    [params.social]
    facebook      = "https://www.facebook.com/thec3uk"
    email         = "hello@thec3.uk"
    twitter       = "https://twitter.com/the_c3church"
    instagram     = "https://www.instagram.com/the_c3church/"
    github        = "https://github.com/thec3uk"