[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "./netlify/header-based-gating"
    [plugins.inputs]
    http_header_name = "secret"
[[plugins]]
  package = "@netlify/plugin-nextjs"

