// Code generated by Slice Machine. DO NOT EDIT.

import Button from './Button';
import Card from './Card';
import Footer from './Footer';
import Header from './Header';
import Link from './Link';
import Media from './Media';
import Text from './Text';

export {
	Button,
	Card,
	Footer,
	Header,
	Link,
	Media,
	Text,
};

export const components = {
	button: Button,
	card: Card,
	footer: Footer,
	header: Header,
	link: Link,
	media: Media,
	text: Text,
};
