// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  button: dynamic(() => import("./Button")),
  card: dynamic(() => import("./Card")),
  contact_form: dynamic(() => import("./ContactForm")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  link: dynamic(() => import("./Link")),
  media: dynamic(() => import("./Media")),
  text: dynamic(() => import("./Text")),
};
